/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import event.PublicEvent;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;
import swing.PictureBox;

/**
 *
 * @author TrongFlorida
 */
public class ChatImage extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatImage
     */
    public ChatImage(boolean right) {
        initComponents();
        setLayout(new MigLayout("", "0[" +(right ? "right" : "left")+ "]0", "3[]3"));// căn về bên phải nếu là chat right, ngược lại
    }
    
    public void addChatImage(Icon... images) {//... là tham số động
        for (Icon img : images) {
            PictureBox pic = new PictureBox();
            pic.setPreferredSize(getAutoSize(img, 200, 200));
            pic.setImage(img);
            addEvent(pic, img);
            add(pic, "wrap");
        }
    }
    
    public void addChatImage(String... images) {//... là tham số động Overloading
        for (String img : images) {
            ImageItem pic = new ImageItem();
            pic.setPreferredSize(new Dimension(200, 200)); // test
            pic.setImageDecoder(img);
//            addEvent(pic, img);
            add(pic, "wrap");
        }
    }
    
    private void addEvent(Component com, Icon image) { //Component chứa các thành phần như button, label, ...
        com.setCursor(new Cursor(Cursor.HAND_CURSOR));
        com.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    EventQueue.invokeLater(() -> {// đưa vào hàng đợi event để tránh lỗi xung đột
                        PublicEvent.getInstance().geEventImageView().viewImage(image);// hiện lên khi ấn vào hình   
                    });
                }
            }
            
        });
    }
    
    private Dimension getAutoSize(Icon image, int w, int h) {
        if(w > image.getIconWidth()) {
            w = image.getIconWidth();
        }
        if(h > image.getIconHeight()) {
            h = image.getIconHeight();
        }
        int iw = image.getIconWidth();
        int ih = image.getIconHeight();
        double xScale = (double) w / iw;
        double yScale = (double) h / ih;
        double scale = Math.min(xScale, yScale);
        int width = (int) (scale * iw);
        int height = (int) (scale * ih);
        return new Dimension(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
