/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import event.IEventMenuLeft;
import event.IEventMenuRight;
import event.PublicEvent;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author TrongFlorida
 */
public class MenuRight extends javax.swing.JPanel {
    String[] languages = {
            "Phát hiện ngôn ngữ", "Afrikaans", "Arabic", "Bulgarian", "Bengali", "Czech", "Danish", "German", "Greek",
            "English", "Spanish", "Estonian", "Persian", "Finnish", "French", "Gujarati", "Hebrew",
            "Hindi", "Croatian", "Hungarian", "Indonesian", "Italian", "Japanese", "Kannada", "Korean",
            "Lithuanian", "Latvian", "Macedonian", "Malayalam", "Marathi", "Nepali", "Dutch", "Norwegian",
            "Punjabi", "Polish", "Portuguese", "Romanian", "Russian", "Slovak", "Slovenian", "Somali",
            "Albanian", "Swedish", "Swahili", "Tamil", "Telugu", "Thai", "Tagalog", "Turkish",
            "Ukrainian", "Urdu", "Vietnamese", "Chinese (Simplified)", "Chinese (Traditional)"
        };

        // Mảng chứa mã code tương ứng
        String[] languagesCode = {
            "auto", "af", "ar", "bg", "bn", "cs", "da", "de", "el",
            "en", "es", "et", "fa", "fi", "fr", "gu", "he",
            "hi", "hr", "hu", "id", "it", "ja", "kn", "ko",
            "lt", "lv", "mk", "ml", "mr", "ne", "nl", "no",
            "pa", "pl", "pt", "ro", "ru", "sk", "sl", "so",
            "sq", "sv", "sw", "ta", "te", "th", "tl", "tr",
            "uk", "ur", "vi", "zh-cn", "zh-tw"
        };
    
    /**
     * Creates new form MenuLeft
     */
    public MenuRight() {
        initComponents();
        initLanguageComboBoxes();
    }
    
    private void initLanguageComboBoxes() {
        // Tạo danh sách ngôn ngữ cần dịch
        
        
        // Tạo DefaultComboBoxModel và thêm danh sách ngôn ngữ vào model
        DefaultComboBoxModel<String> languageModel = new DefaultComboBoxModel<>(languages);

        // Thiết lập model cho JComboBox ngôn ngữ cần dịch
        sourceLanguageComboBox.setModel(languageModel);

        // Clone model để sử dụng cho JComboBox ngôn ngữ dịch
        DefaultComboBoxModel<String> targetLanguageModel = new DefaultComboBoxModel<>(languages);

        // Thiết lập model cho JComboBox ngôn ngữ dịch
        targetLanguageComboBox.setModel(targetLanguageModel);
        
        BtnSourceLanguage.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnSourceLanguageActionPerformed(evt);
        }
    });
    
        BtnTranslateLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTargetLanguageActionPerformed(evt);
            }
        });
       
    }
    
    //Quay lại ngôn ngữ gốc
    private void BtnSourceLanguageActionPerformed(java.awt.event.ActionEvent evt) {        
        // Gọi phương thức để dịch lại lịch sử chat trong ChatBox
        PublicEvent.getInstance().getEventChat().originalChatHistory();
    }

    //Dịch ngôn ngữ
    private void BtnTargetLanguageActionPerformed(java.awt.event.ActionEvent evt) {
        int sourceLanguageIndex = sourceLanguageComboBox.getSelectedIndex();
        int targetLanguageIndex = targetLanguageComboBox.getSelectedIndex();
        String selectedSourceLanguage = languagesCode[sourceLanguageIndex];
        String selectedTargetLanguage = languagesCode[targetLanguageIndex];
        System.out.println("form.MenuRight.BtnTargetLanguageActionPerformed(): "+ selectedSourceLanguage + selectedTargetLanguage);
        // Gọi phương thức để dịch lại lịch sử chat trong ChatBox
        PublicEvent.getInstance().getEventChat().translateChatHistory(selectedSourceLanguage, selectedTargetLanguage);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceLanguageComboBox = new javax.swing.JComboBox<>();
        targetLanguageComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnSourceLanguage = new javax.swing.JButton();
        BtnTranslateLanguage = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 249, 249));

        sourceLanguageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sourceLanguageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceLanguageComboBoxActionPerformed(evt);
            }
        });

        targetLanguageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Chọn ngôn ngữ cần dịch");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Chọn ngôn ngữ dịch sang");

        BtnSourceLanguage.setText("Quay lại");

        BtnTranslateLanguage.setText("Dịch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceLanguageComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnSourceLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTranslateLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addComponent(targetLanguageComboBox, 0, 244, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sourceLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(targetLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSourceLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTranslateLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void sourceLanguageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceLanguageComboBoxActionPerformed
        // Lấy ngôn ngữ được chọn từ nguồn và đích
        String selectedSourceLanguage = (String) sourceLanguageComboBox.getSelectedItem();
        String selectedTargetLanguage = (String) targetLanguageComboBox.getSelectedItem();

        // In ra console hoặc xử lý theo nhu cầu của bạn
        System.out.println("Source Language: " + selectedSourceLanguage);
        System.out.println("Target Language: " + selectedTargetLanguage);
    
    }//GEN-LAST:event_sourceLanguageComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSourceLanguage;
    private javax.swing.JButton BtnTranslateLanguage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> sourceLanguageComboBox;
    private javax.swing.JComboBox<String> targetLanguageComboBox;
    // End of variables declaration//GEN-END:variables
}
